export const CATEGORY_WIKI = [
    {
        "slug": "writing",
        "name": "Writing",
        "meta_title": "What is writing?",
        "meta_content": "",
        "paragraph": "Writing is the act of expressing thoughts, ideas, and emotions through the use of written language. It is a fundamental form of communication that allows individuals to convey information, tell stories, express opinions, and explore the depths of human imagination. A skilled writer possesses the capacity to adapt their writing style to various audiences and purposes, whether it's persuasive, informative, or creative. They can organize thoughts coherently, develop engaging narratives, and employ persuasive techniques to captivate readers. Writing as a skill requires practice, attention to detail, and a willingness to continuously improve and refine one's written expression. ",
        "source": ""
    },
    {
        "slug": "creative-writing",
        "name": "Creative Writing",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Creative writing is the process of crafting original and imaginative works of literature, poetry, prose, or scripts. It transcends conventional writing, encouraging individuals to explore language, structure, and narrative. Whether it's a heartfelt poem, a captivating short story, or a thought-provoking novel, creative writing allows us to communicate our unique perspectives and experiences with the world. Creative writing is a remarkable voyage that invites us to unleash our imagination, share our stories, and inspire others. It offers countless personal and professional benefits, nurturing self-expression, empathy, and creativity. So, grab a pen, open your mind, and embark on this enchanting journey of creative writing.",
        "source": "https://oxfordsummercourses.com/articles/what-is-creative-writing/"
    },
    {
        "slug": "poetry",
        "name": "Poetry",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Poetry is a literary art form that can be written, spoken, or performed. It focuses on the aesthetics of language. It is usually composed in verse and is concerned with evoking an image or emotion. Poetry makes liberal use of literary devices, such as alliteration and metaphor. It is the musicality of language, the rendering of abstract thoughts, ideas, and emotions, rendered with words and sounds. It is pictures painted with words.",
        "source": "https://www.writingforward.com/poetry-writing/what-is-poetry"
    },
    {
        "slug": "spoken-words",
        "name": "Spoken Words",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Spoken word poetry is a word-based performance art where speakers engage in powerful self-expression by sharing their views on particular topics for a live audience, focusing on sound and presentation. Spoken word performances require memorization, performative body language (like gestures and facial expressions), enunciation, and eye contact with viewers.",
        "source": "https://www.masterclass.com/articles/how-to-write-spoken-word-poetry"
    },
    {
        "slug": "photography",
        "name": "Photography",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Photography is the art of capturing light with a camera, usually via a digital sensor or film, to create an image. With the right camera equipment, you can even photograph wavelengths of light invisible to the human eye, including UV, infrared, and radio. There are many different types of photography, such as landscape, macro, wildlife, portrait, documentary, fashion, travel and event photography.",
        "source": "https://photographylife.com/what-is-photography"
    },
    {
        "slug": "illustration",
        "name": "Illustration",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "An illustration is a visualization that is made by an artist. The goal of each illustration is to explain information. It can be a drawing, a photograph, a collage, etc. It doesn’t matter. As long as it keeps its purpose – to visually represent facts and details. Illustrators are trained professionals who can draw in a variety of media not limited to pen and pencil, but also, especially in today’s hyper-digital world, digital image-making",
        "source": "https://graphicmama.com/blog/what-is-illustration/",
    },
    {
        "slug": "painting",
        "name": "Painting",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Painting is the act or process of using paint. The paint can create an artwork known as a painting, or it can be used more practically as a protective coating or form of decoration. Paintings are a form of visual art that captures the expression of ideas and emotions on a two-dimensional surface.",
        "source": "https://www.eden-gallery.com/news/what-is-painting",
    },
    {
        "slug": "caricature-drawing",
        "name": "Caricature Drawing",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Caricature is a drawing style that often shows up as extreme portraits of political figures or wacky boardwalk souvenirs. But there’s more to caricatures than just big noses and other exaggerated facial features. Creating whimsical depictions of people — from the media or real life — by drawing caricatures can help you get better at illustrating real, three-dimensional characters. “A caricature gets to the essence of who someone is and not just what they look like, but what their personality is,” says caricaturist Greg Bigoni.",
        "source": "https://www.adobe.com/creativecloud/illustration/discover/how-to-draw-caricature.html",
    },
    {
        "slug": "art-journaling",
        "name": "Art Journaling",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Simply put, Art Journaling is a visual diary--it's record keeping combined with creativity! It’s a place to record your thoughts, memories, and emotions through images, art and words. An art journal is the same as a written journal, except that it incorporates colors, images, patterns, and other materials. Some art journals have a lot of writing, while others are purely filled with images. It’s a form of creative self-care.",
        "source": "https://shoptangiebaxter.com/pages/what-is-art-journaling",
    },
    {
        "slug": "bullet-journaling",
        "name": "Bullet Journaling",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Bullet Journaling is just one of many journaling methods that can improve your mental health, boost creativity, and even help you sleep better. But it differs from most types of journaling in that it specifically involves goal planning, organization, and, in many cases, wildly creative visual imagery. Bullet Journaling allows you to organize your mind and life while also expressing your individual style.",
        "source": "https://www.dailyom.com/journal/bullet-journaling-for-beginners-tips-to-get-started/",
    },
    {
        "slug": "calligraphy",
        "name": "Calligraphy",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Calligraphy is more than beautiful handwriting or ornate lettering techniques. Calligraphy is the art of forming beautiful symbols by hand and arranging them well. It is a set of skills and techniques for positioning and inscribing words so they show integrity, harmony, some sort of ancestry, rhythm and creative fire.",
        "source": "https://www.calligraphy-skills.com/what-is-calligraphy.html",
    },
    {
        "slug": "calligraphy",
        "name": "Calligraphy",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Calligraphy is more than beautiful handwriting or ornate lettering techniques. Calligraphy is the art of forming beautiful symbols by hand and arranging them well. It is a set of skills and techniques for positioning and inscribing words so they show integrity, harmony, some sort of ancestry, rhythm and creative fire.",
        "source": "https://www.calligraphy-skills.com/what-is-calligraphy.html",
    },
    {
        "slug": "choreography",
        "name": "Choreography",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "It’s the art of creating and arranging dances. a choreographer creates a routine for a dancer (or a group of dancers) to perform. Choreographers incorporate a range of elements into their work, including music, floor patterns, a narrative or storyline, the expression of emotions, and the audience’s perception.",
        "source": "",
    },
    {
        "slug": "collage-making",
        "name": "Collage Making",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Collage is an art form which is made up of overlapping pieces of material, such as photographs, fabric, coloured and textured paper and other types of mixed media. The process focuses on the act of selecting materials and cutting them into the desired shape, before arranging them and pasting them onto the chosen surface.",
        "source": "https://www.riseart.com/guide/2371/a-guide-to-collage",
    },
    {
        "slug": "creative-journaling",
        "name": "Creative Journaling",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Creative journals are essentially a place for you to store your creative ideas, practice your art and overall hone your skills. With it, you can keep your creative juices flowing and your motivation to create art going strong.",
        "source": "https://blog.journey.cloud/how-to-start-a-creative-journal",
    },
    {
        "slug": "dancing",
        "name": "Dancing",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Dancing is the act of rhythmically moving the body and feet. This is usually done to music, and the dancer often follows an established pattern of steps. Styles range from ballroom, which is danced by couples, to performance arts like ballet, where individuals dance as part of a troupe.",
        "source": "https://reference.jrank.org/fitness/Dance.html",
    },
    {
        "slug": "digital-art",
        "name": "Digital Art",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Digital art is any artwork that draws upon digital technology as an essential part of its creative process. It encompasses a wide range of techniques, from digital drawings, paintings and illustration, to photos, videos and even sculpture. All can be classed as digital art, so long as they’re created, enhanced or exhibited digitally.",
        "source": "https://www.adobe.com/uk/creativecloud/illustration/discover/digital-art.html",
    },
    {
        "slug": "doodling",
        "name": "Doodling",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Doodling is the act of creating drawings in an unconscious or unfocused manner. While it may be considered rude to doodle during classes at school, or in a meeting at work, doodling can actually be incredibly beneficial.",
        "source": "https://www.thisiscalmer.com/blog/what-are-benefits-of-doodling",
    },
    {
        "slug": "guitar-playing",
        "name": "Guitar Playing",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "A guitar musician is a person who creates, composes, and/or performs music played on the guitar. A guitar musician may perform by himself or he may join a music band to combine the sound of his instrument with those of other musicians. The guitarist may also accompany his guitar playing with singing, though not all guitarists will do so.",
        "source": "https://www.musicalexpert.org/what-is-a-guitar-musician.htm",
    },
    {
        "slug": "hand-lettering",
        "name": "Hand Lettering",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Hand lettering is an art form that involves drawing letters by hand. Hand lettering allows artists to interpret letters in creative ways. The art of lettering varies depending on the style and the artist doing the lettering.",
        "source": "https://www.vectornator.io/blog/hand-lettering",
    },
    {
        "slug": "journaling",
        "name": "Journaling",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Journaling is the act of expressing your deepest thoughts and feelings by putting words to your inner life and then putting these words on paper. Journaling is a mental, emotional and spiritual exercise that helps you build strong “emotional muscles” to deal with life’s difficulties and uncertainties.",
        "source": "https://www.thecoach.zone/journaling-what-is-it-and-how-to-do-it/",
    },
    {
        "slug": "journaling",
        "name": "Journaling",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "A musician is a person who composes and/or performs music, usually as an occupation but often as a hobby. He or she may play a musical instrument or several musical instruments, or he or she may be a vocalist instead.",
        "source": "https://www.musicalexpert.org/what-is-a-musician.htm",
    },
    {
        "slug": "scrapbooking",
        "name": "Scrapbooking",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Scrapbooking, a crafting and documenting activity, involves taking books with blank pages and adding photos, memorabilia, journaling, and embellishments. Also known as cropping, the primary purpose of scrapbooking is to preserve memories for future generations, but a secondary purpose often is to exercise your creativity as you display your memories in a scrapbook.",
        "source": "https://www.thesprucecrafts.com/what-is-scrapbooking-2960505",
    },
    {
        "slug": "singing",
        "name": "Singing",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Singing is the act of vocalizing melodies and is an attempt to create a blend of pitch, timbre, and rhythm. It is an expression of emotion and communication through musical sounds that are often sung in a variety of musical genres, including musical theatre, opera, popular music, classical music, jazz and folk music.",
        "source": "https://www.quora.com/What-is-the-definition-of-singing",
    },
    {
        "slug": "sketching",
        "name": "Sketching",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "It is about making a quick drawing, a study, which helps you to represent a design idea. It typically use quick marks and simple lines to capture only the essential elements of the subject matter. A sketch will usually lack many of the details that a finished drawing would have. ",
        "source": "https://www.eden-gallery.com/news/drawing-vs-sketching",
    },
    {
        "slug": "standup-comedy",
        "name": "Standup Comedy",
        "meta_title": "What is creative writing?",
        "meta_content": "",
        "paragraph": "Stand-up comedy is literally a comedian who tells funny stories through comedic performances by speaking directly to a live audience in an attempt to get that audience laughing.",
        "source": "https://cleancomedians.com/what-is-stand-up-comedy/",
    },
]