export const FETCH_USER_ANALYTICS = 'FETCH_USER_ANALYTICS';
export const FETCH_USER_ANALYTICS_REQUEST = 'FETCH_USER_ANALYTICS_REQUEST';
export const FETCH_USER_ANALYTICS_SUCCESS = 'FETCH_USER_ANALYTICS_SUCCESS';
export const FETCH_USER_ANALYTICS_FAILURE = 'FETCH_USER_ANALYTICS_FAILURE';

export const FETCH_COLLAB_ANALYTICS = 'FETCH_COLLAB_ANALYTICS';
export const FETCH_COLLAB_ANALYTICS_REQUEST = 'FETCH_COLLAB_ANALYTICS_REQUEST';
export const FETCH_COLLAB_ANALYTICS_SUCCESS = 'FETCH_COLLAB_ANALYTICS_SUCCESS';
export const FETCH_COLLAB_ANALYTICS_FAILURE = 'FETCH_COLLAB_ANALYTICS_FAILURE';
