export const SET_SELETECTED_ID = 'SET_SELECTED_ID';
export const FETCH_ARTIST_BY_CATEGORY = 'FETCH_ARTIST_BY_CATEGORY';
export const FETCH_ARTIST_BY_CATEGORY_REQUEST = 'FETCH_ARTIST_BY_CATEGORY_REQUEST';
export const FETCH_ARTIST_BY_CATEGORY_SUCCESS = 'FETCH_ARTIST_BY_CATEGORY_SUCCESS';
export const FETCH_ARTIST_BY_CATEGORY_FAILURE = 'FETCH_ARTIST_BY_CATEGORY_FAILURE';