export const SET_SELETECTED_CATEGORY_ID = 'SET_SELECTED_CATEGORY_ID';
export const SET_SELETECTED_CATEGORY_SLUG = 'SET_SELETECTED_CATEGORY_SLUG';
export const FETCH_ARTIST_BY_CATEGORY_ID = 'FETCH_ARTIST_BY_CATEGORY_ID';
export const FETCH_ARTIST_BY_CATEGORY_ID_REQUEST = 'FETCH_ARTIST_BY_CATEGORY_ID_REQUEST';
export const FETCH_ARTIST_BY_CATEGORY_ID_SUCCESS = 'FETCH_ARTIST_BY_CATEGORY_ID_SUCCESS';
export const FETCH_ARTIST_BY_CATEGORY_ID_FAILURE = 'FETCH_ARTIST_BY_CATEGORY_ID_FAILURE';

export const FETCH_ARTIST_BY_CATEGORY_SLUG = 'FETCH_ARTIST_BY_CATEGORY_SLUG';
export const FETCH_ARTIST_BY_CATEGORY_SLUG_REQUEST = 'FETCH_ARTIST_BY_CATEGORY_SLUG_REQUEST';
export const FETCH_ARTIST_BY_CATEGORY_SLUG_SUCCESS = 'FETCH_ARTIST_BY_CATEGORY_SLUG_SUCCESS';
export const FETCH_ARTIST_BY_CATEGORY_SLUG_FAILURE = 'FETCH_ARTIST_BY_CATEGORY_SLUG_FAILURE';

export const FETCH_ALL_PUBLISHED_CATEGORIES = 'FETCH_ALL_PUBLISHED_CATEGORIES'
export const FETCH_ALL_PUBLISHED_CATEGORIES_REQUEST = 'FETCH_ALL_PUBLISHED_CATEGORIES_REQUEST'
export const FETCH_ALL_PUBLISHED_CATEGORIES_SUCCESS = 'FETCH_ALL_PUBLISHED_CATEGORIES_SUCCESS'
export const FETCH_ALL_PUBLISHED_CATEGORIES_FAILURE = 'FETCH_ALL_PUBLISHED_CATEGORIES_FAILURE'

export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES'
export const FETCH_ALL_CATEGORIES_REQUEST = 'FETCH_ALL_CATEGORIES_REQUEST'
export const FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS'
export const FETCH_ALL_CATEGORIES_FAILURE = 'FETCH_ALL_CATEGORIES_FAILURE'

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const SET_SHOW_CATEGORY_MODAL = 'SET_SHOW_CATEGORY_MODAL';