
export const SEND_COLLAB_REQUEST = "COLLAB/SEND_COLLAB_REQUEST"
export const REJECT_COLLAB_REQUEST = "COLLAB/REJECT_REQUEST"
export const ACCEPT_COLLAB_REQUEST = "COLLAB/ACCEPT_REQUEST"
export const SEARCH_COLLAB_REQUEST = "COLLAB/SEARCH_COLLAB_REQUEST"
export const SET_PENDING_COLLAB_REQUEST_DATA = "COLLAB/SET_PENDING_COLLAB_REQUEST_DATA"
export const SET_ACTIVE_COLLAB_REQUEST_DATA = "COLLAB/SET_ACTIVE_COLLAB_REQUEST_DATA"
export const SET_COMPLETED_COLLAB_REQUEST_DATA = "COLLAB/SET_COMPLETED_COLLAB_REQUEST_DATA"
export const SET_REJECTED_COLLAB_REQUEST_DATA = "COLLAB/SET_REJECTED_COLLAB_REQUEST_DATA"