export const FETCH_ALL_CONTESTS = 'FETCH_ALL_CONTESTS';
export const FETCH_ALL_CONTESTS_REQUEST = 'FETCH_ALL_CONTESTS_REQUEST';
export const FETCH_ALL_CONTESTS_SUCCESS = 'FETCH_ALL_CONTESTS_SUCCESS';
export const FETCH_ALL_CONTESTS_FAILURE = 'FETCH_ALL_CONTESTS_FAILURE';

export const FETCH_CONTEST = 'FETCH_CONTEST';
export const FETCH_CONTEST_REQUEST = 'FETCH_CONTEST_REQUEST';
export const FETCH_CONTEST_SUCCESS = 'FETCH_CONTEST_SUCCESS';
export const FETCH_CONTEST_FAILURE = 'FETCH_CONTEST_FAILURE';

export const ADD_CONTEST = 'ADD_CONTEST';
export const ADD_CONTEST_REQUEST = 'ADD_CONTEST_REQUEST';
export const ADD_CONTEST_SUCCESS = 'ADD_CONTEST_SUCCESS';
export const ADD_CONTEST_FAILURE = 'ADD_CONTEST_FAILURE';

export const UPDATE_CONTEST = 'UPDATE_CONTEST';
export const UPDATE_CONTEST_REQUEST = 'UPDATE_CONTEST_REQUEST';
export const UPDATE_CONTEST_SUCCESS = 'UPDATE_CONTEST_SUCCESS';
export const UPDATE_CONTEST_FAILURE = 'UPDATE_CONTEST_FAILURE';

export const SET_SHOW_CONTEST_MODAL = 'SET_SHOW_CONTEST_MODAL';

export const FETCH_ARTIST_SUBMISSION = 'FETCH_ARTIST_SUBMISSION';
export const FETCH_ARTIST_SUBMISSION_REQUEST = 'FETCH_ARTIST_SUBMISSION_REQUEST';
export const FETCH_ARTIST_SUBMISSION_SUCCESS = 'FETCH_ARTIST_SUBMISSION_SUCCESS';
export const FETCH_ARTIST_SUBMISSION_FAILURE = 'FETCH_ARTIST_SUBMISSION_FAILURE';


export const FETCH_CONTEST_SUBMISSIONS = 'FETCH_CONTEST_SUBMISSIONS';
export const FETCH_CONTEST_SUBMISSIONS_REQUEST = 'FETCH_CONTEST_SUBMISSIONS_REQUEST';
export const FETCH_CONTEST_SUBMISSIONS_SUCCESS = 'FETCH_CONTEST_SUBMISSIONS_SUCCESS';
export const FETCH_CONTEST_SUBMISSIONS_FAILURE = 'FETCH_CONTEST_SUBMISSIONS_FAILURE';