export const SEND_EMAIL_TO_ONE_USER = 'SEND_EMAIL_TO_ONE_USER';
export const SEND_EMAIL_TO_ONE_USER_REQUEST = 'SEND_EMAIL_TO_ONE_USER_REQUEST';
export const SEND_EMAIL_TO_ONE_USER_SUCCESS = 'SEND_EMAIL_TO_ONE_USER_SUCCESS';
export const SEND_EMAIL_TO_ONE_USER_FAILURE = 'SEND_EMAIL_TO_ONE_USER_FAILURE';

export const SEND_EMAIL_TO_SLUG = 'SEND_EMAIL_TO_SLUG';
export const SEND_EMAIL_TO_SLUG_REQUEST = 'SEND_EMAIL_TO_SLUG_REQUEST';
export const SEND_EMAIL_TO_SLUG_SUCCESS = 'SEND_EMAIL_TO_SLUG_SUCCESS';
export const SEND_EMAIL_TO_SLUG_FAILURE = 'SEND_EMAIL_TO_SLUG_FAILURE';

export const SEND_EMAIL_TO_ALL_USERS = 'SEND_EMAIL_TO_ALL_USERS';
export const SEND_EMAIL_TO_ALL_USERS_REQUEST = 'SEND_EMAIL_TO_ALL_USERS_REQUEST';
export const SEND_EMAIL_TO_ALL_USERS_SUCCESS = 'SEND_EMAIL_TO_ALL_USERS_SUCCESS';
export const SEND_EMAIL_TO_ALL_USERS_FAILURE = 'SEND_EMAIL_TO_ALL_USERS_FAILURE';

export const SEND_EMAIL_TO_GROUP = 'SEND_EMAIL_TO_GROUP';
export const SEND_EMAIL_TO_GROUP_REQUEST = 'SEND_EMAIL_TO_GROUP_REQUEST';
export const SEND_EMAIL_TO_GROUP_SUCCESS = 'SEND_EMAIL_TO_GROUP_SUCCESS';
export const SEND_EMAIL_TO_GROUP_FAILURE = 'SEND_EMAIL_TO_GROUP_FAILURE';

export const FETCH_ALL_EMAIL_ENUMS = 'FETCH_ALL_EMAIL_ENUMS';
export const FETCH_ALL_EMAIL_ENUMS_SUCCESS = 'FETCH_ALL_EMAIL_ENUMS_SUCCESS';
