export const SEND_EMAIL_TO_ONE_USER = 'SEND_EMAIL_TO_ONE_USER';
export const SEND_EMAIL_TO_ONE_USER_REQUEST = 'SEND_EMAIL_TO_ONE_USER_REQUEST';
export const SEND_EMAIL_TO_ONE_USER_SUCCESS = 'SEND_EMAIL_TO_ONE_USER_SUCCESS';
export const SEND_EMAIL_TO_ONE_USER_FAILURE = 'SEND_EMAIL_TO_ONE_USER_FAILURE';

export const SEND_EMAIL_TO_ALL_USERS = 'SEND_EMAIL_TO_ALL_USERS';
export const SEND_EMAIL_TO_ALL_USERS_REQUEST = 'SEND_EMAIL_TO_ALL_USERS_REQUEST';
export const SEND_EMAIL_TO_ALL_USERS_SUCCESS = 'SEND_EMAIL_TO_ALL_USERS_SUCCESS';
export const SEND_EMAIL_TO_ALL_USERS_FAILURE = 'SEND_EMAIL_TO_ALL_USERS_FAILURE';
