export const HOME = "HOME";
export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL";
export const FETCH_LOGIN_DATA = "FETCH_LOGIN_DATA";
export const UPDATE_LOGIN_DATA = "UPDATE_LOGIN_DATA";
export const SET_IS_LOADING = "SET_IS_LOADING";