export const ADD_PROPOSAL_QUESTION = 'ADD_PROPOSAL_QUESTION';
export const ADD_PROPOSAL_QUESTION_REQUEST = 'ADD_PROPOSAL_QUESTION_REQUEST';
export const ADD_PROPOSAL_QUESTION_SUCCESS = 'ADD_PROPOSAL_QUESTION_SUCCESS';
export const ADD_PROPOSAL_QUESTION_FAILURE = 'ADD_PROPOSAL_QUESTION_FAILURE';


export const ADD_PROPOSAL_ANSWER = 'ADD_PROPOSAL_ANSWER';
export const ADD_PROPOSAL_ANSWER_REQUEST = 'ADD_PROPOSAL_ANSWER_REQUEST';
export const ADD_PROPOSAL_ANSWER_SUCCESS = 'ADD_PROPOSAL_ANSWER_SUCCESS';
export const ADD_PROPOSAL_ANSWER_FAILURE = 'ADD_PROPOSAL_ANSWER_FAILURE';


export const FETCH_PROPOSAL_ALL_QUESTIONS_BY_PROPOSAL_ID = 'FETCH_PROPOSAL_ALL_QUESTIONS_BY_PROPOSAL_ID'
export const FETCH_PROPOSAL_ALL_QUESTIONS_BY_PROPOSAL_ID_REQUEST = 'FETCH_PROPOSAL_ALL_QUESTIONS_BY_PROPOSAL_ID_REQUEST'
export const FETCH_PROPOSAL_ALL_QUESTIONS_BY_PROPOSAL_ID_SUCCESS = 'FETCH_PROPOSAL_ALL_QUESTIONS_BY_PROPOSAL_ID_SUCCESS'
export const FETCH_PROPOSAL_ALL_QUESTIONS_BY_PROPOSAL_ID_FAILURE = 'FETCH_PROPOSAL_ALL_QUESTIONS_BY_PROPOSAL_ID_FAILURE'