export const FETCH_ALL_PROPOSALS = 'FETCH_ALL_PROPOSALS'
export const FETCH_ALL_PROPOSALS_REQUEST = 'FETCH_ALL_PROPOSALS_REQUEST'
export const FETCH_ALL_PROPOSALS_SUCCESS = 'FETCH_ALL_PROPOSALS_SUCCESS'
export const FETCH_ALL_PROPOSALS_FAILURE = 'FETCH_ALL_PROPOSALS_FAILURE'

export const ADD_PROPOSAL = 'ADD_PROPOSAL';
export const ADD_PROPOSAL_REQUEST = 'ADD_PROPOSAL_REQUEST';
export const ADD_PROPOSAL_SUCCESS = 'ADD_PROPOSAL_SUCCESS';
export const ADD_PROPOSAL_FAILURE = 'ADD_PROPOSAL_FAILURE';

export const UPDATE_PROPOSAL = 'UPDATE_PROPOSAL';
export const UPDATE_PROPOSAL_REQUEST = 'UPDATE_PROPOSAL_REQUEST';
export const UPDATE_PROPOSAL_SUCCESS = 'UPDATE_PROPOSAL_SUCCESS';
export const UPDATE_PROPOSAL_FAILURE = 'UPDATE_PROPOSAL_FAILURE';


export const FETCH_PROPOSAL_BY_ID = 'FETCH_PROPOSAL_BY_ID';
export const FETCH_PROPOSAL_BY_ID_REQUEST = 'FETCH_PROPOSAL_BY_ID_REQUEST';
export const FETCH_PROPOSAL_BY_ID_SUCCESS = 'FETCH_PROPOSAL_BY_ID_SUCCESS';
export const FETCH_PROPOSAL_BY_ID_FAILURE = 'FETCH_PROPOSAL_BY_ID_FAILURE';


export const FETCH_PROPOSAL_BY_ARTIST_SLUG = 'FETCH_PROPOSAL_BY_ARTIST_SLUG';
export const FETCH_PROPOSAL_BY_ARTIST_SLUG_REQUEST = 'FETCH_PROPOSAL_BY_ARTIST_SLUG_REQUEST';
export const FETCH_PROPOSAL_BY_ARTIST_SLUG_SUCCESS = 'FETCH_PROPOSAL_BY_ARTIST_SLUG_SUCCESS';
export const FETCH_PROPOSAL_BY_ARTIST_SLUG_FAILURE = 'FETCH_PROPOSAL_BY_ARTIST_SLUG_FAILURE';