export const FETCH_ALL_PROPOSAL_INTERESTS = 'FETCH_ALL_PROPOSAL_INTERESTS'
export const FETCH_ALL_PROPOSAL_INTERESTS_REQUEST = 'FETCH_ALL_PROPOSAL_INTERESTS_REQUEST'
export const FETCH_ALL_PROPOSAL_INTERESTS_SUCCESS = 'FETCH_ALL_PROPOSAL_INTERESTS_SUCCESS'
export const FETCH_ALL_PROPOSAL_INTERESTS_FAILURE = 'FETCH_ALL_PROPOSAL_INTERESTS_FAILURE'

export const ADD_PROPOSAL_INTEREST = 'ADD_PROPOSAL_INTEREST';
export const ADD_PROPOSAL_INTEREST_REQUEST = 'ADD_PROPOSAL_INTEREST_REQUEST';
export const ADD_PROPOSAL_INTEREST_SUCCESS = 'ADD_PROPOSAL_INTEREST_SUCCESS';
export const ADD_PROPOSAL_INTEREST_FAILURE = 'ADD_PROPOSAL_INTEREST_FAILURE';

export const ACCEPT_PROPOSAL_INTEREST = 'ACCEPT_PROPOSAL_INTEREST';
export const ACCEPT_PROPOSAL_INTEREST_REQUEST = 'ACCEPT_PROPOSAL_INTEREST_REQUEST';
export const ACCEPT_PROPOSAL_INTEREST_SUCCESS = 'ACCEPT_PROPOSAL_INTEREST_SUCCESS';
export const ACCEPT_PROPOSAL_INTEREST_FAILURE = 'ACCEPT_PROPOSAL_INTEREST_FAILURE';

export const REJECT_PROPOSAL_INTEREST = 'REJECT_PROPOSAL_INTEREST';
export const REJECT_PROPOSAL_INTEREST_REQUEST = 'REJECT_PROPOSAL_INTEREST_REQUEST';
export const REJECT_PROPOSAL_INTEREST_SUCCESS = 'REJECT_PROPOSAL_INTEREST_SUCCESS';
export const REJECT_PROPOSAL_INTEREST_FAILURE = 'REJECT_PROPOSAL_INTEREST_FAILURE';


export const SHOW_PROPOSAL_INTERESTED_ARTIST_MODAL = 'SHOW_PROPOSAL_INTERESTED_ARTIST_MODAL';