export const FETCH_PROPOSAL_COMMENT_BY_PROPOSAL_ID = 'FETCH_PROPOSAL_COMMENT_BY_PROPOSAL _ID';
export const FETCH_PROPOSAL_COMMENT_BY_PROPOSAL_ID_REQUEST = 'FETCH_PROPOSAL_COMMENT_BY_PROPOSAL _ID_REQUEST';
export const FETCH_PROPOSAL_COMMENT_BY_PROPOSAL_ID_SUCCESS = 'FETCH_PROPOSAL_COMMENT_BY_PROPOSAL _ID_SUCCESS';
export const FETCH_PROPOSAL_COMMENT_BY_PROPOSAL_ID_FAILURE = 'FETCH_PROPOSAL_COMMENT_BY_PROPOSAL _ID_FAILURE';

export const ADD_PROPOSAL_COMMENT = 'ADD_PROPOSAL_COMMENT ';
export const ADD_PROPOSAL_COMMENT_REQUEST = 'ADD_PROPOSAL_COMMENT _REQUEST';
export const ADD_PROPOSAL_COMMENT_SUCCESS = 'ADD_PROPOSAL_COMMENT _SUCCESS';
export const ADD_PROPOSAL_COMMENT_FAILURE = 'ADD_PROPOSAL_COMMENT _FAILURE';