export const FETCH_ALL_PROPOSAL_INTERESTS = 'FETCH_ALL_PROPOSAL_INTERESTS'
export const FETCH_ALL_PROPOSAL_INTERESTS_REQUEST = 'FETCH_ALL_PROPOSAL_INTERESTS_REQUEST'
export const FETCH_ALL_PROPOSAL_INTERESTS_SUCCESS = 'FETCH_ALL_PROPOSAL_INTERESTS_SUCCESS'
export const FETCH_ALL_PROPOSAL_INTERESTS_FAILURE = 'FETCH_ALL_PROPOSAL_INTERESTS_FAILURE'

export const ADD_PROPOSAL_INTEREST = 'ADD_PROPOSAL_INTEREST';
export const ADD_PROPOSAL_INTEREST_REQUEST = 'ADD_PROPOSAL_INTEREST_REQUEST';
export const ADD_PROPOSAL_INTEREST_SUCCESS = 'ADD_PROPOSAL_INTEREST_SUCCESS';
export const ADD_PROPOSAL_INTEREST_FAILURE = 'ADD_PROPOSAL_INTEREST_FAILURE';

export const SHOW_PROPOSAL_INTERESTED_ARTIST_MODAL = 'SHOW_PROPOSAL_INTERESTED_ARTIST_MODAL';