export const FETCH_REWARDS_ACTIVITY = 'FETCH_REWARDS_ACTIVITY';
export const FETCH_REWARDS_ACTIVITY_REQUEST = 'FETCH_REWARDS_ACTIVITY_REQUEST';
export const FETCH_REWARDS_ACTIVITY_SUCCESS = 'FETCH_REWARDS_ACTIVITY_SUCCESS';
export const FETCH_REWARDS_ACTIVITY_FAILURE = 'FETCH_REWARDS_ACTIVITY_FAILURE';

export const FETCH_REWARDS = 'FETCH_REWARDS';
export const FETCH_REWARDS_REQUEST = 'FETCH_REWARDS_REQUEST';
export const FETCH_REWARDS_SUCCESS = 'FETCH_REWARDS_SUCCESS';
export const FETCH_REWARDS_FAILURE = 'FETCH_REWARDS_FAILURE';

export const VERIFY_REFFERAL_CODE = 'VERIFY_REFFERAL_CODE';
export const VERIFY_REFFERAL_CODE_REQUEST = 'VERIFY_REFFERAL_CODE_REQUEST';
export const VERIFY_REFFERAL_CODE_SUCCESS = 'VERIFY_REFFERAL_CODE_SUCCESS';
export const VERIFY_REFFERAL_CODE_FAILURE = 'VERIFY_REFFERAL_CODE_FAILURE';


export const SKIP_REFFERAL_CODE = 'SKIP_REFFERAL_CODE';
export const SKIP_REFFERAL_CODE_REQUEST = 'SKIP_REFFERAL_CODE_REQUEST';
export const SKIP_REFFERAL_CODE_SUCCESS = 'SKIP_REFFERAL_CODE_SUCCESS';
export const SKIP_REFFERAL_CODE_FAILURE = 'SKIP_REFFERAL_CODE_FAILURE';