export const FETCH_REWARDS_ACTIVITY = 'FETCH_REWARDS_ACTIVITY';
export const FETCH_REWARDS_ACTIVITY_REQUEST = 'FETCH_REWARDS_ACTIVITY_REQUEST';
export const FETCH_REWARDS_ACTIVITY_SUCCESS = 'FETCH_REWARDS_ACTIVITY_SUCCESS';
export const FETCH_REWARDS_ACTIVITY_FAILURE = 'FETCH_REWARDS_ACTIVITY_FAILURE';

export const FETCH_REWARDS = 'FETCH_REWARDS';
export const FETCH_REWARDS_REQUEST = 'FETCH_REWARDS_REQUEST';
export const FETCH_REWARDS_SUCCESS = 'FETCH_REWARDS_SUCCESS';
export const FETCH_REWARDS_FAILURE = 'FETCH_REWARDS_FAILURE';