export const FETCH_SCRATCHPAD_BY_ARTIST_ID = 'FETCH_SCRATCHPAD_BY_ARTIST_ID';
export const FETCH_SCRATCHPAD_BY_ARTIST_ID_REQUEST = 'FETCH_SCRATCHPAD_BY_ARTIST_ID_REQUEST';
export const FETCH_SCRATCHPAD_BY_ARTIST_ID_SUCCESS = 'FETCH_SCRATCHPAD_BY_ARTIST_ID_SUCCESS';
export const FETCH_SCRATCHPAD_BY_ARTIST_ID_FAILURE = 'FETCH_SCRATCHPAD_BY_ARTIST_ID_FAILURE';

export const UPDATE_ARTIST_SCRATCHPAD = 'UPDATE_ARTIST_SCRATCHPAD';
export const UPDATE_ARTIST_SCRATCHPAD_REQUEST = 'UPDATE_ARTIST_SCRATCHPAD_REQUEST';
export const UPDATE_ARTIST_SCRATCHPAD_SUCCESS = 'UPDATE_ARTIST_SCRATCHPAD_SUCCESS';
export const UPDATE_ARTIST_SCRATCHPAD_FAILURE = 'UPDATE_ARTIST_SCRATCHPAD_FAILURE';